// Auto-generated by uptime-pocket-ios-widget plugin.
// This file is the Swift→ObjC bridging header for the
// main app target. Imports React so Swift can call
// back into the React Native bridge.
#import <React/RCTBridgeModule.h>
