/**
 * Re-exports for the UI primitives module.
 *
 * We explicitly re-export icons (not `export *`) to avoid
 * collision with our own components (Tag, Server, etc.).
 */

export { Button, type ButtonVariant, type ButtonSize } from './Button';
export { Chip } from './Chip';
export { SegmentedControl, type SegmentOption } from './SegmentedControl';
export { Tag } from './Tag';
export { EmptyState } from './EmptyState';
export { ErrorState } from './ErrorState';

// Icons - explicit named exports to avoid clashing with our components
export {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  BellOff,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleDashed,
  Clock,
  Copy,
  Database,
  Edit,
  Eye,
  EyeOff,
  ExternalLink,
  Filter,
  Globe,
  Hash,
  Heart,
  HeartPulse,
  HelpCircle,
  Info,
  KeyRound,
  Link2,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Maximize2,
  Menu,
  MessageSquare,
  Minimize2,
  MoreHorizontal,
  MoreVertical,
  Pause,
  Pencil,
  Play,
  Plus,
  Power,
  Radio,
  RefreshCw,
  RotateCw,
  Save,
  Search,
  Send,
  Server,
  ServerCrash,
  ServerOff,
  Settings,
  Share2,
  Shield,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  Slash,
  Sliders,
  Smartphone,
  Sparkles,
  Star,
  Trash2,
  TrendingDown,
  TrendingUp,
  Unlock,
  User,
  Users,
  Wifi,
  WifiOff,
  X,
  Zap,
  monitorTypeIcon,
  ICON_SIZES,
  type IconProps,
  type LucideIcon,
  type LucideProps,
} from './icons';
